In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder, StandardScaler

In [2]:
df = pd.read_excel("imdb_ratings.xlsx")
df.head()

   Unnamed: 0    titleId                   title  averageRating  numVotes
0           0  tt0000001              Carmencita            5.7      1676
1           1  tt0000002  Le clown et ses chiens            6.1       208
2           2  tt0000003          Pauvre Pierrot            6.5      1404
3           3  tt0000004             Un bon bock            6.2       123
4           4  tt0000005        Blacksmith Scene            6.2      2200

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67408 entries, 0 to 67407
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     67408 non-null  int64
 1   titleId        67408 non-null  object
 2   title          67408 non-null  object
 3   averageRating  67408 non-null  float64
 4   numVotes       67408 non-null  int64
dtypes: float64(1), int64(2), object(2)
memory usage: 2.6+ MB

In [4]:
df = df.drop(columns=['Unnamed: 0'])

In [5]:
df.isnull().sum()

titleId          0
title            0
averageRating    0
numVotes         0
dtype: int64

In [6]:
df.describe()

       averageRating      numVotes
count   67408.000000  6.740800e+04
mean        6.354568  2.408154e+03
std         1.351718  2.320630e+04
min         1.000000  5.000000e+00
25%         5.600000  1.800000e+01
50%         6.500000  7.500000e+01
75%         7.300000  3.680000e+02
max        10.000000  1.515727e+06

In [7]:
le = LabelEncoder()
df['titleId_encoded'] = le.fit_transform(df['titleId'])

In [8]:
scaler = StandardScaler()

df[['averageRating', 'numVotes']] = scaler.fit_transform(
    df[['averageRating', 'numVotes']]
)

In [9]:
df['vote_category'] = pd.cut(
    df['numVotes'],
    bins=[-2, -0.5, 0, 0.5, 3],
    labels=['Very Low', 'Low', 'Medium', 'High']
)

In [10]:
df['rating_class'] = pd.cut(
    df['averageRating'],
    bins=[-2, -0.5, 0.5, 3],
    labels=['Low', 'Average', 'High']
)

In [11]:
df = pd.get_dummies(
    df,
    columns=['vote_category', 'rating_class'],
    drop_first=True
)

In [12]:
df.corr(numeric_only=True)

,averageRating,numVotes,titleId_encoded,vote_category_Low,vote_category_Medium,vote_category_High,rating_class_Average,rating_class_High
averageRating,1.000000,0.063430,0.070857,-0.098303,0.065945,0.054973,0.021363,0.711109
numVotes,0.063430,1.000000,-0.017118,-0.317813,0.033027,0.162087,-0.022974,0.066244
titleId_encoded,0.070857,-0.017118,1.000000,0.050621,-0.040407,-0.023263,-0.111198,0.131442
vote_category_Low,-0.098303,-0.317813,0.050621,1.000000,-0.832111,-0.444537,0.018884,-0.099616
vote_category_Medium,0.065945,0.033027,-0.040407,-0.832111,1.000000,-0.032058,-0.013066,0.068396
vote_category_High,0.054973,0.162087,-0.023263,-0.444537,-0.032058,1.000000,-0.006611,0.052112
rating_class_Average,0.021363,-0.022974,-0.111198,0.018884,-0.013066,-0.006611,1.000000,-0.577278
rating_class_High,0.711109,0.066244,0.131442,-0.099616,0.068396,0.052112,-0.577278,1.000000

In [13]:
df.corr(numeric_only=True)['averageRating'].sort_values(ascending=False)

averageRating           1.000000
rating_class_High       0.711109
titleId_encoded         0.070857
vote_category_Medium    0.065945
numVotes                0.063430
vote_category_High      0.054973
rating_class_Average    0.021363
vote_category_Low      -0.098303
Name: averageRating, dtype: float64

In [14]:
df_model = df.drop(columns=['title', 'titleId'])
df_model.head()

,averageRating,numVotes,titleId_encoded,vote_category_Low,vote_category_Medium,vote_category_High,rating_class_Average,rating_class_High
0,-0.484252,-0.031550,0,True,False,False,True,False
1,-0.188330,-0.094809,1,True,False,False,True,False
2,0.107591,-0.043271,2,True,False,False,True,False
3,-0.114350,-0.098472,3,True,False,False,True,False
4,-0.114350,-0.008970,4,True,False,False,True,False

In [15]:
df_model.shape

(67408, 8)

In [16]:
df_model.to_csv("imdb_task3_transformed.csv", index=False)

In Task 3, feature understanding and data transformation were performed on the IMDb ratings dataset. Irrelevant columns were removed, categorical variables were encoded using Label Encoding and One-Hot Encoding, and numerical features were standardized using StandardScaler. Additional features such as vote categories and rating classes were engineered to enhance interpretability. Correlation analysis was conducted to identify important features. The final transformed dataset is clean, normalized, and ready for analysis and machine learning modeling.